using System.Text;
using Dashboards_reports.CollectionTracker.Domain;
using Dashboards_reports.CollectionTracker.Dtos;
using Dashboards_reports.CollectionTracker.Repositories;

namespace Dashboards_reports.CollectionTracker.Services;

/// <summary>
/// Shared logic for executing a scheduled report: load clients → build deterministic HTML → send email.
/// All report narratives are now generated by rule-based templates (no AI).
/// Used by both the controller (run-now / preview) and the background scheduler.
/// </summary>
public static class ReportExecutor
{
    // Default fallback buckets — used only if DB load fails
    private static readonly Dictionary<string, HashSet<string>> DefaultBuckets = new(StringComparer.OrdinalIgnoreCase)
    {
        ["resolved"] = new(StringComparer.OrdinalIgnoreCase) { "resolved" },
        ["cancellation"] = new(StringComparer.OrdinalIgnoreCase) { "cancellation", "pending cancellation", "loan status: declined" },
        ["approved"] = new(StringComparer.OrdinalIgnoreCase) { "loan approved: loan docs signing/bv/si", "takeout processing" },
        ["delivered"] = new(StringComparer.OrdinalIgnoreCase) { "takeout processing" },
        ["on-process"] = new(StringComparer.OrdinalIgnoreCase) { "loan approved: loan docs signing/bv/si", "annotation of title (pag-ibig only)", "annotated title submitted (pag-ibig only)", "takeout processing" },
        ["for-process"] = new(StringComparer.OrdinalIgnoreCase) { "client document compliance", "submit to bank/pag-ibig", " institutional findings (optional)" },
    };

    private static async Task<Dictionary<string, HashSet<string>>> LoadBucketMapAsync(
        IClientRepository clientRepository,
        CancellationToken cancellationToken)
    {
        try
        {
            var buckets = await clientRepository.GetStageBucketsAsync(cancellationToken);
            var allStages = await clientRepository.GetAllBucketStagesAsync(cancellationToken);
            var stagesByBucket = allStages.GroupBy(s => s.BucketId)
                .ToDictionary(g => g.Key, g => g.Select(s => s.StageName).ToHashSet(StringComparer.OrdinalIgnoreCase));

            var map = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);
            foreach (var bucket in buckets)
            {
                map[bucket.Key] = stagesByBucket.GetValueOrDefault(bucket.Id, new HashSet<string>(StringComparer.OrdinalIgnoreCase));
            }
            return map;
        }
        catch
        {
            return DefaultBuckets;
        }
    }

    private static HashSet<string> GetBucket(Dictionary<string, HashSet<string>> bucketMap, string key) =>
        bucketMap.GetValueOrDefault(key, []);

    // ─────────────────────────────────────────────────────────────────────
    // Public entry points
    // ─────────────────────────────────────────────────────────────────────

    public static async Task ExecuteScheduleAsync(
        ScheduledReport schedule,
        IClientRepository clientRepository,
        IEmailService emailService,
        IScheduledReportRepository scheduleRepository,
        CancellationToken cancellationToken)
    {
        try
        {
            var recipients = System.Text.Json.JsonSerializer.Deserialize<List<string>>(schedule.Recipients) ?? [];
            if (recipients.Count == 0)
            {
                await scheduleRepository.UpdateRunStatusAsync(
                    schedule.Id, DateTime.UtcNow, "error", "No recipients configured.", cancellationToken);
                return;
            }

            var (html, note) = await GenerateReportAsync(
                schedule.ReportType ?? "client-risk", schedule.ProjectId, clientRepository, cancellationToken);

            if (html is null)
            {
                await scheduleRepository.UpdateRunStatusAsync(
                    schedule.Id, DateTime.UtcNow, "success", note, cancellationToken);
                return;
            }

            var subject = $"Collection Tracker - {schedule.Name} ({DateTime.UtcNow:MMM dd, yyyy})";
            await emailService.SendHtmlEmailAsync(recipients, subject, html, cancellationToken);

            await scheduleRepository.UpdateRunStatusAsync(
                schedule.Id, DateTime.UtcNow, "success", null, cancellationToken);
        }
        catch (Exception ex)
        {
            await scheduleRepository.UpdateRunStatusAsync(
                schedule.Id, DateTime.UtcNow, "error", ex.Message, cancellationToken);
            throw;
        }
    }

    /// <summary>
    /// Build the HTML for a report type without sending email. Used by the manual preview endpoint.
    /// Returns (html, note). html is null when there's nothing to report (note explains why).
    /// </summary>
    public static async Task<(string? Html, string? Note)> GenerateReportAsync(
        string reportType, int? projectId,
        IClientRepository clientRepository,
        CancellationToken cancellationToken)
    {
        var allClients = await clientRepository.GetClientsAsync(cancellationToken);
        if (projectId.HasValue)
            allClients = allClients.Where(c => c.ProjectId == projectId.Value).ToList();

        var stageOrder = (await clientRepository.GetStagesAsync(cancellationToken))
            .Select(s => s.Name).ToList();

        var today = DateTime.UtcNow.Date;
        var mapped = allClients.Select(c => ClientMapper.ToListItem(c, today, stageOrder)).ToList();
        var bucketMap = await LoadBucketMapAsync(clientRepository, cancellationToken);

        return reportType switch
        {
            "executive-portfolio" =>
                (await BuildExecutivePortfolioAsync(mapped, clientRepository, projectId, bucketMap, cancellationToken), null),
            "collection-performance" =>
                (BuildCollectionPerformance(mapped), null),
            "strategic-recommendations" =>
                (await BuildStrategicRecommendationsAsync(mapped, clientRepository, projectId, bucketMap, cancellationToken), null),
            "collection-forecast" =>
                (await BuildCollectionForecastAsync(mapped, clientRepository, projectId, bucketMap, cancellationToken), null),
            _ => BuildClientRiskReport(mapped, await clientRepository.GetRecentActivitiesAsync(500, 0, cancellationToken))
        };
    }

    // ─────────────────────────────────────────────────────────────────────
    // Report 1: Client Risk Analysis
    // ─────────────────────────────────────────────────────────────────────

    private static (string? Html, string? Note) BuildClientRiskReport(
        List<ClientListItemDto> mapped,
        IReadOnlyList<ActivityLog> recentActivities)
    {
        var atRisk = mapped
            .Where(c => c.AgingStatus is "critical" or "warning" or "watch")
            .OrderByDescending(c => c.TotalContractPrice ?? 0)
            .ToList();

        if (atRisk.Count == 0)
            return (null, "No at-risk clients found.");

        var sevenDaysAgo = DateTime.UtcNow.AddDays(-7);
        var weeklyActivities = recentActivities.Where(a => a.ActivityDateTime >= sevenDaysAgo).ToList();
        var activitiesByClientId = weeklyActivities
            .GroupBy(a => a.ClientId)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(a => a.ActivityDateTime).ToList());

        var active = mapped.Where(c => !c.IsResolved && !c.IsCancelled).ToList();
        var totalTcpAtRisk = atRisk.Sum(c => c.TotalContractPrice ?? 0);

        var teamProductivity = weeklyActivities
            .GroupBy(a => string.IsNullOrWhiteSpace(a.CreatedBy) ? "Unassigned" : a.CreatedBy!)
            .Select(g => new { Name = g.Key, Count = g.Count() })
            .OrderByDescending(x => x.Count)
            .ToList();

        var noActivityClients = atRisk.Where(c => !activitiesByClientId.ContainsKey(c.Id)).ToList();
        var overdueFollowUps = atRisk.Count(c => c.FollowUpDate.HasValue && c.FollowUpDate.Value < DateTime.UtcNow);

        var resolvedThisWeek = mapped
            .Where(c => c.IsResolved && c.ResolvedDate.HasValue && c.ResolvedDate.Value >= sevenDaysAgo)
            .ToList();

        var brokerStats = atRisk
            .Where(c => !string.IsNullOrWhiteSpace(c.BrokerName))
            .GroupBy(c => c.BrokerName!, StringComparer.OrdinalIgnoreCase)
            .Select(g => new
            {
                Broker = g.Key,
                Count = g.Count(),
                TotalTcp = g.Sum(x => x.TotalContractPrice ?? 0)
            })
            .OrderByDescending(b => b.TotalTcp)
            .Take(8)
            .ToList();

        var sb = new StringBuilder();
        sb.Append(OpenContainer());
        sb.Append(BuildReportHeader("Client Risk Analysis", "Higher-management view of at-risk accounts and team activity"));

        // ── Management Summary Dashboard ──
        sb.Append(SectionDivider("📊 Management Summary"));
        sb.Append(KpiHero("Total TCP at Risk", FormatPeso(totalTcpAtRisk),
            $"{atRisk.Count} at-risk clients &middot; {active.Count} total active"));

        sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:16px;\"><tr>");
        sb.Append(KpiCell("Critical", active.Count(c => c.AgingStatus == "critical").ToString(), "#D32F2F", "#FFEBEE"));
        sb.Append(KpiCell("Warning", active.Count(c => c.AgingStatus == "warning").ToString(), "#ED6C02", "#FFF3E0"));
        sb.Append(KpiCell("Watch", active.Count(c => c.AgingStatus == "watch").ToString(), "#F9A825", "#FFFDE7"));
        sb.Append(KpiCell("Overdue", overdueFollowUps.ToString(), "#8B0000", "rgba(139,0,0,0.08)"));
        sb.Append("</tr></table>");

        // ── Weekly Activity Summary ──
        sb.Append(SectionDivider("📅 Weekly Activity Summary"));
        sb.Append($"<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px 18px;margin-bottom:16px;\">"
                + $"<div style=\"font-size:13px;color:#475569;\">"
                + $"<strong style=\"color:#1f2937;\">{weeklyActivities.Count}</strong> activities recorded in the last 7 days &middot; "
                + $"<strong style=\"color:#D32F2F;\">{noActivityClients.Count}</strong> at-risk accounts had zero activity"
                + $"</div></div>");

        if (teamProductivity.Count > 0)
        {
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append(SubBanner("TEAM RESPONSIVENESS & PRODUCTIVITY"));
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            var maxProd = teamProductivity[0].Count;
            for (var i = 0; i < teamProductivity.Count; i++)
            {
                var t = teamProductivity[i];
                var width = maxProd > 0 ? (int)Math.Round((double)t.Count / maxProd * 100) : 0;
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}width:40%;\">{Html(t.Name)}</td>"
                        + $"<td style=\"{TdStyle}width:50%;\">"
                        + $"<div style=\"background:#e5e7eb;border-radius:4px;height:8px;\">"
                        + $"<div style=\"background:#8B0000;border-radius:4px;height:8px;width:{width}%;\"></div></div></td>"
                        + $"<td style=\"{TdRStyle}width:10%;font-weight:700;\">{t.Count}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── Accounts Needing Immediate Attention ──
        if (noActivityClients.Count > 0 || overdueFollowUps > 0)
        {
            sb.Append(SectionDivider("🚨 Accounts Needing Immediate Attention"));
            sb.Append("<div style=\"background:#FFEBEE;border-left:4px solid #D32F2F;border-radius:8px;padding:14px 18px;margin-bottom:16px;\">");
            if (noActivityClients.Count > 0)
            {
                sb.Append($"<div style=\"font-size:13px;color:#C62828;font-weight:700;margin-bottom:6px;\">⚠ {noActivityClients.Count} at-risk account(s) had ZERO activity this week:</div>");
                sb.Append("<div style=\"font-size:12px;color:#475569;line-height:1.7;\">");
                sb.Append(string.Join(" &bull; ", noActivityClients.Take(20).Select(c => Html(c.Name))));
                if (noActivityClients.Count > 20) sb.Append($" &middot; <em>and {noActivityClients.Count - 20} more</em>");
                sb.Append("</div>");
            }
            if (overdueFollowUps > 0)
            {
                sb.Append($"<div style=\"font-size:13px;color:#C62828;font-weight:700;margin-top:10px;\">⚠ {overdueFollowUps} client(s) have overdue follow-up dates.</div>");
            }
            sb.Append("</div>");
        }

        // ── Weekly Resolutions ──
        if (resolvedThisWeek.Count > 0)
        {
            sb.Append(SectionDivider("✅ Weekly Resolutions"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append("<tr style=\"background:#E8F5E9;\">"
                    + $"<td style=\"{ThStyle}\">Client</td>"
                    + $"<td style=\"{ThStyle}\">Project</td>"
                    + $"<td style=\"{ThStyle}\">Unit</td>"
                    + $"<td style=\"{ThStyle}\">Resolved As</td>"
                    + $"<td style=\"{ThStyle}\">Date</td></tr>");
            for (var i = 0; i < resolvedThisWeek.Count; i++)
            {
                var r = resolvedThisWeek[i];
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}\">{Html(r.Name)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(r.ProjectName)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(r.Unit)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(r.ResolvedHow ?? "—")}</td>"
                        + $"<td style=\"{TdStyle}\">{(r.ResolvedDate.HasValue ? FmtDate(r.ResolvedDate.Value) : "—")}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── Broker performance ──
        if (brokerStats.Count > 0)
        {
            sb.Append(SectionDivider("👥 Broker / Agent Performance (At-Risk Accounts)"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append("<tr style=\"background:#F7FAFC;\">"
                    + $"<td style=\"{ThStyle}\">Broker</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">At-Risk Clients</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Total TCP at Risk</td></tr>");
            for (var i = 0; i < brokerStats.Count; i++)
            {
                var b = brokerStats[i];
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}\">{Html(b.Broker)}</td>"
                        + $"<td style=\"{TdRStyle}\">{b.Count}</td>"
                        + $"<td style=\"{TdRStyle}\">{FormatPeso(b.TotalTcp)}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── Per-client cards grouped by aging ──
        sb.Append(SectionDivider("📋 At-Risk Accounts Detail"));
        var critical = atRisk.Where(c => c.AgingStatus == "critical").ToList();
        var warning = atRisk.Where(c => c.AgingStatus == "warning").ToList();
        var watch = atRisk.Where(c => c.AgingStatus == "watch").ToList();
        sb.Append(BuildClientGroup("CRITICAL", critical, "#D32F2F", "#FFEBEE", activitiesByClientId));
        sb.Append(BuildClientGroup("WARNING", warning, "#ED6C02", "#FFF3E0", activitiesByClientId));
        sb.Append(BuildClientGroup("WATCH", watch, "#F9A825", "#FFFDE7", activitiesByClientId));

        // ── Rule-based recommendations ──
        sb.Append(SectionDivider("💡 Recommended Actions"));
        sb.Append(BuildClientRiskRecommendations(atRisk, noActivityClients.Count, overdueFollowUps, weeklyActivities.Count, active.Count));

        sb.Append(BuildFooter("Client Risk Analysis"));
        sb.Append("</div>");
        return (sb.ToString(), null);
    }

    private static string BuildClientGroup(string label, List<ClientListItemDto> clients, string color, string bg,
        Dictionary<int, List<ActivityLog>> activitiesByClientId)
    {
        if (clients.Count == 0) return "";
        var sb = new StringBuilder();
        sb.Append($"<div style=\"margin-bottom:16px;\"><div style=\"background:{bg};border-left:4px solid {color};padding:8px 14px;border-radius:6px;margin-bottom:10px;\">"
                + $"<span style=\"font-size:11px;font-weight:800;color:{color};letter-spacing:1.2px;\">{label}</span>"
                + $"<span style=\"font-size:11px;color:#475569;margin-left:8px;\">{clients.Count} account(s)</span></div>");

        foreach (var c in clients)
        {
            var tcp = c.TotalContractPrice ?? 0;
            sb.Append($"<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px 18px;margin-bottom:10px;\">");
            sb.Append($"<div style=\"display:flex;justify-content:space-between;align-items:flex-start;flex-wrap:wrap;gap:10px;\">");
            sb.Append($"<div>"
                    + $"<div style=\"font-size:14px;font-weight:700;color:#1f2937;\">{Html(c.Name)}</div>"
                    + $"<div style=\"font-size:11px;color:#64748b;margin-top:2px;\">{Html(c.ProjectName)} &bull; Unit {Html(c.Unit)} &bull; {Html(c.FinancingType)}</div>"
                    + $"</div>");
            sb.Append($"<div style=\"text-align:right;\"><div style=\"font-size:14px;font-weight:800;color:#1f2937;\">{FormatPeso(tcp)}</div>"
                    + $"<div style=\"font-size:11px;color:#64748b;\">{c.DaysInStage} days in {Html(c.Stage)}</div></div>");
            sb.Append("</div>");

            // Issue details
            sb.Append("<div style=\"font-size:11.5px;color:#475569;margin-top:10px;line-height:1.6;\">");
            if (c.DelayReasons.Count > 0)
                sb.Append($"<div><strong style=\"color:#1f2937;\">Delay reasons:</strong> {Html(string.Join(", ", c.DelayReasons))}</div>");
            if (!string.IsNullOrWhiteSpace(c.NextAction))
                sb.Append($"<div><strong style=\"color:#1f2937;\">Next action:</strong> {Html(c.NextAction)}</div>");
            if (!string.IsNullOrWhiteSpace(c.BrokerName))
                sb.Append($"<div><strong style=\"color:#1f2937;\">Broker:</strong> {Html(c.BrokerName)}</div>");
            if (c.OverdueTaskCount > 0 || c.PendingTaskCount > 0)
                sb.Append($"<div><strong style=\"color:#1f2937;\">Tasks:</strong> {c.PendingTaskCount} pending, "
                        + $"<span style=\"color:{(c.OverdueTaskCount > 0 ? "#D32F2F" : "#475569")};font-weight:600;\">{c.OverdueTaskCount} overdue</span></div>");
            if (c.IsTargetOverdue && c.TargetDate.HasValue)
                sb.Append($"<div style=\"color:#D32F2F;\"><strong>⚠ Target date passed:</strong> {FmtDate(c.TargetDate.Value)}</div>");
            sb.Append("</div>");

            // Weekly activities
            var weekly = activitiesByClientId.GetValueOrDefault(c.Id, new List<ActivityLog>());
            sb.Append("<div style=\"margin-top:10px;padding-top:10px;border-top:1px dashed #e5e7eb;\">"
                    + "<div style=\"font-size:10px;color:#64748b;font-weight:700;letter-spacing:0.8px;text-transform:uppercase;margin-bottom:6px;\">This Week's Activities</div>");
            if (weekly.Count == 0)
            {
                sb.Append("<div style=\"background:#FFEBEE;color:#C62828;padding:6px 10px;border-radius:6px;font-size:11.5px;font-weight:700;\">⚠ No activity recorded this week</div>");
            }
            else
            {
                sb.Append("<div style=\"font-size:11.5px;color:#475569;line-height:1.7;\">");
                foreach (var a in weekly.Take(5))
                {
                    sb.Append($"<div>&middot; <strong>{FmtDate(a.ActivityDateTime)}</strong> &mdash; "
                            + $"<em>{Html(a.ActivityType)}</em>: {Html(a.Description)} "
                            + $"<span style=\"color:#9ca3af;\">({Html(a.CreatedBy ?? "—")})</span></div>");
                }
                if (weekly.Count > 5)
                    sb.Append($"<div style=\"color:#9ca3af;font-style:italic;\">…and {weekly.Count - 5} more</div>");
                sb.Append("</div>");
            }
            sb.Append("</div>");

            sb.Append("</div>");
        }

        sb.Append("</div>");
        return sb.ToString();
    }

    private static string BuildClientRiskRecommendations(
        List<ClientListItemDto> atRisk, int noActivityCount, int overdueFollowUps,
        int weeklyActivities, int activeCount)
    {
        var sb = new StringBuilder();
        var recs = new List<(string Priority, string Color, string Title, string Body)>();

        var criticalCount = atRisk.Count(c => c.AgingStatus == "critical");
        var criticalTcp = atRisk.Where(c => c.AgingStatus == "critical").Sum(c => c.TotalContractPrice ?? 0);

        if (criticalCount > 0)
            recs.Add(("IMMEDIATE", "#D32F2F",
                $"Triage {criticalCount} critical account(s) within 24-48 hours",
                $"Critical accounts represent {FormatPeso(criticalTcp)} in TCP. Top 5 by value should get direct manager outreach today."));

        if (noActivityCount > 0)
            recs.Add(("IMMEDIATE", "#D32F2F",
                $"Re-engage {noActivityCount} silent at-risk account(s)",
                "No activity in 7 days on an at-risk account is a leading indicator of cancellation. Assign owners by tomorrow."));

        if (overdueFollowUps > 0)
            recs.Add(("SHORT-TERM", "#ED6C02",
                $"Clear {overdueFollowUps} overdue follow-up(s) this week",
                "Each overdue follow-up erodes client trust. Reschedule or close them out within 5 business days."));

        if (activeCount > 0 && weeklyActivities < activeCount)
            recs.Add(("SHORT-TERM", "#ED6C02",
                "Lift activity floor across active portfolio",
                $"Only {weeklyActivities} activities recorded for {activeCount} active accounts this week. Set a minimum of one touchpoint per active account per week."));

        var topDelayReason = atRisk.SelectMany(c => c.DelayReasons)
            .Where(r => !string.IsNullOrWhiteSpace(r))
            .GroupBy(r => r, StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(g => g.Count())
            .FirstOrDefault();
        if (topDelayReason != null)
            recs.Add(("STRATEGIC", "#8B0000",
                $"Address root cause: \"{Html(topDelayReason.Key)}\"",
                $"This reason appears in {topDelayReason.Count()} at-risk client(s). Investigate process or training gap behind it."));

        if (recs.Count == 0)
            recs.Add(("STRATEGIC", "#2E7D32", "Maintain current cadence", "No urgent flags detected this period. Continue current outreach pattern and monitor weekly."));

        foreach (var (priority, color, title, body) in recs)
        {
            sb.Append($"<div style=\"background:#fff;border:1px solid #e5e7eb;border-left:4px solid {color};border-radius:8px;padding:12px 16px;margin-bottom:8px;\">"
                    + $"<span style=\"display:inline-block;background:{color};color:#fff;font-size:10px;font-weight:800;padding:2px 8px;border-radius:10px;letter-spacing:0.6px;\">{priority}</span>"
                    + $"<div style=\"font-size:13px;font-weight:700;color:#1f2937;margin-top:6px;\">{title}</div>"
                    + $"<div style=\"font-size:12px;color:#475569;margin-top:4px;line-height:1.55;\">{body}</div></div>");
        }
        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Report 2: Executive Portfolio Summary (was already deterministic)
    // ─────────────────────────────────────────────────────────────────────

    private static async Task<string> BuildExecutivePortfolioAsync(
        List<ClientListItemDto> mapped,
        IClientRepository clientRepository,
        int? projectId,
        Dictionary<string, HashSet<string>> bucketMap,
        CancellationToken cancellationToken)
    {
        var projects = await clientRepository.GetProjectsAsync(cancellationToken);
        if (projectId.HasValue)
            projects = projects.Where(p => p.Id == projectId.Value).ToList();

        var now = DateTime.UtcNow;
        var selectedYear = now.Year;
        var selectedMonth = now.Month - 1;
        var weekEndDates = GetWeekEndDates(selectedYear, selectedMonth);
        var monthLabels = new[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };

        var projectUnitsMap = new Dictionary<int, IReadOnlyList<ProjectUnit>>();
        foreach (var p in projects)
            projectUnitsMap[p.Id] = await clientRepository.GetProjectUnitsAsync(p.Id, cancellationToken);

        var weeklyInsightsMap = new Dictionary<int, List<InsightSnapshot>>();
        foreach (var project in projects)
        {
            var units = projectUnitsMap.GetValueOrDefault(project.Id, []);
            var insights = new List<InsightSnapshot>();
            foreach (var cutoff in weekEndDates)
            {
                var cutoffEnd = cutoff.Date.AddDays(1).AddTicks(-1);
                var fc = mapped.Where(c =>
                {
                    if (c.ProjectId != project.Id) return false;
                    var effectiveDate = GetEffectiveDate(c, bucketMap);
                    if (effectiveDate == null) return true;
                    return effectiveDate.Value <= cutoffEnd;
                }).ToList();
                insights.Add(ComputeInsight(project, units, fc, bucketMap));
            }
            weeklyInsightsMap[project.Id] = insights;
        }

        List<InsightSnapshot>? consolidated = null;
        if (!projectId.HasValue)
        {
            consolidated = new List<InsightSnapshot>();
            for (var w = 0; w < weekEndDates.Count; w++)
            {
                var weekInsights = projects
                    .Where(p => weeklyInsightsMap.ContainsKey(p.Id) && weeklyInsightsMap[p.Id].Count > w)
                    .Select(p => weeklyInsightsMap[p.Id][w]).ToList();
                consolidated.Add(AggregateInsights(weekInsights));
            }
        }

        InsightSnapshot? latestInsight = null;
        if (consolidated is { Count: > 0 })
            latestInsight = consolidated[^1];
        else if (projects.Count == 1 && weeklyInsightsMap.ContainsKey(projects[0].Id) && weeklyInsightsMap[projects[0].Id].Count > 0)
            latestInsight = weeklyInsightsMap[projects[0].Id][^1];

        var projectIds = projects.Select(p => p.Id).ToHashSet();
        var totalPortfolioValue = mapped.Where(c => c.ProjectId.HasValue && projectIds.Contains(c.ProjectId.Value))
            .Sum(c => c.TotalContractPrice ?? 0);
        var clientCount = mapped.Count(c => c.ProjectId.HasValue && projectIds.Contains(c.ProjectId.Value));

        decimal soldRate = 0, deliveryRate = 0, cancellationRate = 0, pipelineValue = 0;
        if (latestInsight != null)
        {
            var s = latestInsight;
            var soldBase = s.Total;
            var delBase = s.ForAcceptance + s.FullyPaid;
            var cancBase = s.ForAcceptance + s.FullyPaid + s.ForCancellation;
            soldRate = soldBase > 0 ? (s.ForAcceptance + s.FullyPaid) / soldBase : 0;
            deliveryRate = delBase > 0 ? s.Delivered / delBase : 0;
            cancellationRate = cancBase > 0 ? s.ForCancellation / cancBase : 0;
            pipelineValue = s.OnProcess + s.ForProcess;
        }

        var activeClients = mapped.Where(c => !c.IsResolved && !c.IsCancelled && c.ProjectId.HasValue && projectIds.Contains(c.ProjectId.Value)).ToList();
        var bottlenecks = activeClients
            .GroupBy(c => c.Stage, StringComparer.OrdinalIgnoreCase)
            .Select(g => new BottleneckEntry(g.Key, g.Count(), (int)Math.Round(g.Average(c => c.DaysInStage)), g.Sum(c => c.TotalContractPrice ?? 0)))
            .OrderByDescending(x => x.AvgDays).Take(5).ToList();

        var priorMonth = selectedMonth == 0 ? 11 : selectedMonth - 1;
        var priorYear = selectedMonth == 0 ? selectedYear - 1 : selectedYear;
        var priorWeekDates = GetWeekEndDates(priorYear, priorMonth);
        var priorInsights = new List<InsightSnapshot>();
        if (priorWeekDates.Count > 0)
        {
            var lastCutoff = priorWeekDates[^1];
            var cutoffEnd = lastCutoff.Date.AddDays(1).AddTicks(-1);
            foreach (var project in projects)
            {
                var units = projectUnitsMap.GetValueOrDefault(project.Id, []);
                var fc = mapped.Where(c =>
                {
                    if (c.ProjectId != project.Id) return false;
                    var effectiveDate = GetEffectiveDate(c, bucketMap);
                    if (effectiveDate == null) return true;
                    return effectiveDate.Value <= cutoffEnd;
                }).ToList();
                priorInsights.Add(ComputeInsight(project, units, fc, bucketMap));
            }
        }

        var priorMonthLabel = monthLabels[priorMonth];
        List<(string Label, string Key, decimal Current, decimal Prior, decimal Delta)>? momMetrics = null;
        if (priorInsights.Count > 0)
        {
            var priorAgg = AggregateInsights(priorInsights);
            InsightSnapshot? currentEnd = null;
            if (consolidated is { Count: > 0 }) currentEnd = consolidated[^1];
            else if (projects.Count == 1 && weeklyInsightsMap.ContainsKey(projects[0].Id) && weeklyInsightsMap[projects[0].Id].Count > 0)
                currentEnd = weeklyInsightsMap[projects[0].Id][^1];

            if (currentEnd != null)
            {
                momMetrics = new()
                {
                    ("Total", "total", currentEnd.Total, priorAgg.Total, currentEnd.Total - priorAgg.Total),
                    ("For Acceptance", "forAcceptance", currentEnd.ForAcceptance, priorAgg.ForAcceptance, currentEnd.ForAcceptance - priorAgg.ForAcceptance),
                    ("Fully Paid", "fullyPaid", currentEnd.FullyPaid, priorAgg.FullyPaid, currentEnd.FullyPaid - priorAgg.FullyPaid),
                    ("For Cancellation", "forCancellation", currentEnd.ForCancellation, priorAgg.ForCancellation, currentEnd.ForCancellation - priorAgg.ForCancellation),
                    ("Delivered", "delivered", currentEnd.Delivered, priorAgg.Delivered, currentEnd.Delivered - priorAgg.Delivered),
                };
            }
        }

        return BuildExecutiveHtml(
            totalPortfolioValue, soldRate, deliveryRate, cancellationRate, pipelineValue,
            projects, clientCount, weekEndDates, weeklyInsightsMap, consolidated,
            momMetrics, priorMonthLabel, selectedMonth, selectedYear, bottlenecks,
            projectUnitsMap, monthLabels);
    }

    private sealed record BottleneckEntry(string Stage, int Count, int AvgDays, decimal TotalTcp);

    private sealed class InsightSnapshot
    {
        public decimal Unsold, ForAcceptance, FullyPaid, ForCancellation, Total;
        public decimal ApprovedAccount, Delivered, OnProcess, ForProcess, AccountTotal;
        public int UnsoldCount;
    }

    private static DateTime? GetEffectiveDate(ClientListItemDto c, Dictionary<string, HashSet<string>> bucketMap)
    {
        var stage = c.Stage ?? "";
        if (GetBucket(bucketMap, "resolved").Contains(stage) || c.IsResolved)
            return c.ResolvedDate ?? c.StageDate;
        return c.StageDate;
    }

    private static List<DateTime> GetWeekEndDates(int year, int month)
    {
        var daysInMonth = DateTime.DaysInMonth(year, month + 1);
        var dates = new List<DateTime>();
        var day = 7;
        while (day < daysInMonth) { dates.Add(new DateTime(year, month + 1, day)); day += 7; }
        dates.Add(new DateTime(year, month + 1, daysInMonth));
        return dates;
    }

    private static InsightSnapshot ComputeInsight(
        Project project, IReadOnlyList<ProjectUnit> units, List<ClientListItemDto> clients,
        Dictionary<string, HashSet<string>> bucketMap)
    {
        var projectClients = clients.Where(c => c.ProjectId == project.Id).ToList();
        var cancelBucket = GetBucket(bucketMap, "cancellation");
        var occupiedUnits = projectClients
            .Where(c => !cancelBucket.Contains(c.Stage ?? ""))
            .Select(c => c.Unit).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var ins = new InsightSnapshot();

        foreach (var unit in units)
        {
            if (!occupiedUnits.Contains(unit.Name))
            {
                ins.Unsold += unit.TotalContractPrice ?? 0;
                ins.UnsoldCount++;
            }
        }

        foreach (var c in projectClients)
        {
            var tcp = c.TotalContractPrice ?? 0;
            var stage = c.Stage ?? "";
            if (cancelBucket.Contains(stage)) continue;
            if (GetBucket(bucketMap, "resolved").Contains(stage) || c.IsResolved) ins.FullyPaid += tcp;
            else ins.ForAcceptance += tcp;

            if (GetBucket(bucketMap, "approved").Contains(stage)) ins.ApprovedAccount += tcp;
            if (GetBucket(bucketMap, "delivered").Contains(stage)) ins.Delivered += tcp;
            if (GetBucket(bucketMap, "on-process").Contains(stage)) ins.OnProcess += tcp;
            if (GetBucket(bucketMap, "for-process").Contains(stage)) ins.ForProcess += tcp;
        }

        ins.Total = ins.Unsold + ins.ForAcceptance + ins.FullyPaid + ins.ForCancellation;
        ins.AccountTotal = ins.OnProcess + ins.ForProcess;
        return ins;
    }

    private static InsightSnapshot AggregateInsights(List<InsightSnapshot> list)
    {
        var agg = new InsightSnapshot();
        foreach (var s in list)
        {
            agg.Unsold += s.Unsold; agg.UnsoldCount += s.UnsoldCount;
            agg.ForAcceptance += s.ForAcceptance; agg.FullyPaid += s.FullyPaid;
            agg.ForCancellation += s.ForCancellation; agg.Total += s.Total;
            agg.ApprovedAccount += s.ApprovedAccount; agg.Delivered += s.Delivered;
            agg.OnProcess += s.OnProcess; agg.ForProcess += s.ForProcess;
            agg.AccountTotal += s.AccountTotal;
        }
        return agg;
    }

    private static string DeltaColor(string key, decimal delta)
    {
        if (delta == 0) return "neutral";
        var badUp = key is "forCancellation" or "unsold";
        var isUp = delta > 0;
        if (isUp) return badUp ? "error" : "success";
        return badUp ? "success" : "error";
    }

    private static string BuildExecutiveHtml(
        decimal totalPortfolioValue, decimal soldRate, decimal deliveryRate, decimal cancellationRate, decimal pipelineValue,
        IReadOnlyList<Project> projects, int clientCount,
        List<DateTime> weekEndDates,
        Dictionary<int, List<InsightSnapshot>> weeklyInsightsMap,
        List<InsightSnapshot>? consolidated,
        List<(string Label, string Key, decimal Current, decimal Prior, decimal Delta)>? momMetrics,
        string priorMonthLabel, int selectedMonth, int selectedYear,
        List<BottleneckEntry> bottlenecks,
        Dictionary<int, IReadOnlyList<ProjectUnit>> projectUnitsMap,
        string[] monthLabels)
    {
        const string sectionBar = "width:4px;height:18px;background:#8B0000;border-radius:2px;display:inline-block;margin-right:8px;vertical-align:middle;";
        const string badge = "display:inline-block;padding:2px 10px;border-radius:12px;font-size:11px;font-weight:600;margin-right:6px;";

        var h = $"<div style=\"font-family:Inter,Segoe UI,Arial,sans-serif;color:#1A202C;max-width:800px;margin:0 auto;\">";

        h += $"<div style=\"background:linear-gradient(135deg,#1a0000 0%,#8B0000 100%);padding:28px 32px;border-radius:12px;margin-bottom:20px;\">"
           + $"<h1 style=\"margin:0;color:#fff;font-size:22px;font-weight:700;\">Executive Portfolio Summary</h1>"
           + $"<p style=\"margin:4px 0 0;color:rgba(255,255,255,0.7);font-size:13px;\">"
           + $"{monthLabels[selectedMonth]} {selectedYear} &bull; Generated {DateTime.UtcNow:MMM d, yyyy h:mm tt}</p></div>";

        h += $"<div style=\"background:#FFFBF0;border-left:4px solid #D4A017;border-radius:10px;overflow:hidden;padding:20px 24px;margin-bottom:16px;\">"
           + $"<div style=\"font-size:11px;color:#8B7D3C;font-weight:600;text-transform:uppercase;letter-spacing:1px;\">Total Portfolio Value</div>"
           + $"<div style=\"font-size:28px;font-weight:800;color:#1A202C;margin:4px 0;\">{FormatPeso(totalPortfolioValue)}</div>"
           + $"<div style=\"font-size:12px;color:#718096;\">{projects.Count} project{(projects.Count != 1 ? "s" : "")} &bull; {clientCount} clients</div></div>";

        var kpiItems = new[]
        {
            ("Sold Rate", FormatPct(soldRate), "#2E7D32", "#E8F5E9"),
            ("Delivery Rate", FormatPct(deliveryRate), "#1565C0", "#E3F2FD"),
            ("Cancellation Rate", FormatPct(cancellationRate), "#C62828", "#FFEBEE"),
            ("Receivables", FmtCompact(pipelineValue), "#E65100", "#FFF3E0"),
        };
        h += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:20px;\"><tr>";
        for (var i = 0; i < kpiItems.Length; i++)
        {
            var (label, value, color, bg) = kpiItems[i];
            h += $"<td style=\"width:25%;padding:{(i > 0 ? "0 0 0 8px" : "0")};\">"
               + $"<div style=\"background:{bg};border-left:3px solid {color};border-radius:8px;padding:14px 16px;\">"
               + $"<div style=\"font-size:10px;color:{color};font-weight:600;text-transform:uppercase;letter-spacing:0.5px;\">{label}</div>"
               + $"<div style=\"font-size:20px;font-weight:700;color:{color};margin-top:2px;\">{value}</div></div></td>";
        }
        h += "</tr></table>";

        string BuildWeeklyTable(string title, List<InsightSnapshot> insights, List<DateTime> dates, int unitCount, int unsoldCount)
        {
            var t = "";
            t += $"<div style=\"background:linear-gradient(135deg,#2D3748,#4A5568);color:#fff;padding:12px 16px;border-radius:10px 10px 0 0;\">"
               + $"<span style=\"font-size:13px;font-weight:700;\">{title}</span>"
               + $"<span style=\"float:right;\">"
               + $"<span style=\"{badge}background:rgba(255,255,255,0.15);color:#fff;\">{unitCount} units</span>"
               + $"<span style=\"{badge}background:rgba(255,255,255,0.1);color:#CBD5E0;\">{unsoldCount} unsold</span></span></div>";
            t += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #E2E8F0;border-top:none;border-collapse:collapse;\">";

            t += $"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}width:40%;\">AMOUNT AS OF</td>";
            foreach (var d in dates) t += $"<td style=\"{ThStyle}text-align:right;\">{FmtDate(d)}</td>";
            t += "</tr>";

            void SectionHeader(string label)
            {
                t += $"<tr><td colspan=\"{1 + dates.Count}\" style=\"padding:10px 12px;background:#F0F0F0;font-size:11px;font-weight:700;color:#4A5568;\">"
                   + $"<span style=\"{sectionBar}\"></span>{label}</td></tr>";
            }

            void DataRow(string label, string key, Func<InsightSnapshot, decimal> getter, bool alt)
            {
                var values = insights.Select(getter).ToList();
                t += $"<tr style=\"background:{(alt ? "#FAFAFA" : "#fff")};\">"
                   + $"<td style=\"{TdStyle}font-weight:500;\">{label}</td>";
                for (var i = 0; i < values.Count; i++)
                {
                    var deltaHtml = "";
                    if (i > 0)
                    {
                        var delta = values[i] - values[i - 1];
                        if (delta != 0)
                        {
                            var color = DeltaColor(key, delta) == "success" ? "#2E7D32" : "#C62828";
                            var arrow = delta > 0 ? "&#9650;" : "&#9660;";
                            deltaHtml = $"<span style=\"font-size:9px;color:{color};margin-left:4px;\">{arrow}{FmtCompact(Math.Abs(delta))}</span>";
                        }
                    }
                    t += $"<td style=\"{TdRStyle}\">{FmtOrBlank(values[i])}{deltaHtml}</td>";
                }
                t += "</tr>";
            }

            void PctRow(string label, Func<InsightSnapshot, decimal> computeFn)
            {
                t += $"<tr style=\"background:#F7FAFC;\"><td style=\"{TdStyle}font-size:11px;color:#718096;font-style:italic;\">{label}</td>";
                foreach (var ins in insights) t += $"<td style=\"{TdRStyle}font-size:11px;color:#718096;font-style:italic;\">{FormatPct(computeFn(ins))}</td>";
                t += "</tr>";
            }

            void TotalRow(string key, Func<InsightSnapshot, decimal> getter)
            {
                var values = insights.Select(getter).ToList();
                t += $"<tr style=\"background:#EDF2F7;font-weight:700;\"><td style=\"{TdStyle}font-weight:700;\">TOTAL</td>";
                for (var i = 0; i < values.Count; i++)
                {
                    var deltaHtml = "";
                    if (i > 0)
                    {
                        var delta = values[i] - values[i - 1];
                        if (delta != 0)
                        {
                            var color = DeltaColor(key, delta) == "success" ? "#2E7D32" : "#C62828";
                            var arrow = delta > 0 ? "&#9650;" : "&#9660;";
                            deltaHtml = $"<span style=\"font-size:9px;color:{color};margin-left:4px;\">{arrow}{FmtCompact(Math.Abs(delta))}</span>";
                        }
                    }
                    t += $"<td style=\"{TdRStyle}font-weight:700;\">{FormatPeso(values[i])}{deltaHtml}</td>";
                }
                t += "</tr>";
            }

            SectionHeader("INVENTORY STATUS");
            DataRow("Unsold", "unsold", s => s.Unsold, false);
            DataRow("Sold", "forAcceptance", s => s.ForAcceptance, true);
            DataRow("Fully Paid", "fullyPaid", s => s.FullyPaid, false);
            DataRow("For Cancellation", "forCancellation", s => s.ForCancellation, true);
            PctRow("Cancellation %", s => { var b = s.ForAcceptance + s.FullyPaid + s.ForCancellation; return b > 0 ? s.ForCancellation / b : 0; });
            TotalRow("total", s => s.Total);
            PctRow("Sold %", s => s.Total > 0 ? (s.ForAcceptance + s.FullyPaid) / s.Total : 0);

            SectionHeader("ACCOUNT PROCESSING");
            DataRow("Approved Account", "approvedAccount", s => s.ApprovedAccount, false);
            DataRow("Delivered", "delivered", s => s.Delivered, true);
            PctRow("Delivery %", s => { var b = s.ForAcceptance + s.FullyPaid; return b > 0 ? s.Delivered / b : 0; });
            DataRow("On Process", "onProcess", s => s.OnProcess, false);
            DataRow("For Process", "forProcess", s => s.ForProcess, true);
            TotalRow("accountTotal", s => s.AccountTotal);

            t += "</table>";
            return $"<div style=\"border-radius:10px;overflow:hidden;margin-bottom:20px;\">{t}</div>";
        }

        h += "<div style=\"text-align:center;margin:24px 0 16px;color:#718096;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;\">&#128197; Weekly Breakdown</div>";

        if (consolidated != null)
        {
            var totalUnitCount = projects.Sum(p => projectUnitsMap.GetValueOrDefault(p.Id, []).Count);
            var latestUnsold = consolidated.Count > 0 ? consolidated[^1].UnsoldCount : 0;
            h += BuildWeeklyTable("CONSOLIDATED — ALL PROJECTS", consolidated, weekEndDates, totalUnitCount, latestUnsold);
        }

        if (projects.Count > 1)
            h += "<div style=\"text-align:center;margin:20px 0 12px;color:#718096;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;\">By Project</div>";

        foreach (var project in projects)
        {
            if (!weeklyInsightsMap.ContainsKey(project.Id)) continue;
            var weekly = weeklyInsightsMap[project.Id];
            var unitCount = projectUnitsMap.GetValueOrDefault(project.Id, []).Count;
            var latestUnsold = weekly.Count > 0 ? weekly[^1].UnsoldCount : 0;
            h += BuildWeeklyTable($"SUMMARY FOR {project.Name.ToUpper()}", weekly, weekEndDates, unitCount, latestUnsold);
        }

        if (momMetrics is { Count: > 0 })
        {
            h += "<div style=\"text-align:center;margin:24px 0 16px;color:#718096;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;\">&#8644; Month Comparison</div>";
            h += "<div style=\"border-radius:10px;overflow:hidden;border:1px solid #E2E8F0;margin-bottom:20px;\">";
            h += $"<div style=\"background:#F7FAFC;padding:14px 16px;border-bottom:1px solid #E2E8F0;\">"
               + $"<span style=\"font-size:14px;font-weight:700;color:#2D3748;\">Month-over-Month</span>"
               + $"<span style=\"font-size:12px;color:#718096;margin-left:8px;\">{priorMonthLabel} vs {monthLabels[selectedMonth]} {selectedYear}</span></div>";
            h += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">";
            h += $"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}width:10%\"></td>"
               + $"<td style=\"{ThStyle}width:30%\">Metric</td>"
               + $"<td style=\"{ThStyle}text-align:right;width:20%\">{priorMonthLabel}</td>"
               + $"<td style=\"{ThStyle}text-align:right;width:20%\">{monthLabels[selectedMonth]}</td>"
               + $"<td style=\"{ThStyle}text-align:right;width:20%\">Change</td></tr>";

            for (var i = 0; i < momMetrics.Count; i++)
            {
                var m = momMetrics[i];
                var dc = DeltaColor(m.Key, m.Delta);
                var color = dc == "success" ? "#2E7D32" : dc == "error" ? "#C62828" : "#718096";
                var bgColor = dc == "success" ? "#E8F5E9" : dc == "error" ? "#FFEBEE" : "#F7FAFC";
                var arrow = m.Delta > 0 ? "&#9650;" : m.Delta < 0 ? "&#9660;" : "&#8212;";
                h += $"<tr style=\"background:{(i % 2 == 1 ? "#FAFAFA" : "#fff")};\">"
                   + $"<td style=\"{TdStyle}text-align:center;\"><span style=\"display:inline-block;width:24px;height:24px;line-height:24px;border-radius:50%;background:{bgColor};color:{color};font-size:10px;text-align:center;\">{arrow}</span></td>"
                   + $"<td style=\"{TdStyle}font-weight:600;\">{m.Label}</td>"
                   + $"<td style=\"{TdRStyle}\">{FmtCompact(m.Prior)}</td>"
                   + $"<td style=\"{TdRStyle}\">{FmtCompact(m.Current)}</td>"
                   + $"<td style=\"{TdRStyle}color:{color};font-weight:600;\">{(m.Delta > 0 ? "+" : "")}{FmtCompact(m.Delta)}</td></tr>";
            }
            h += "</table></div>";
        }

        if (bottlenecks.Count > 0)
        {
            h += "<div style=\"text-align:center;margin:24px 0 16px;color:#718096;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;\">&#9888; Pipeline Bottleneck Analysis</div>";
            h += "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-radius:10px;overflow:hidden;border:1px solid #E2E8F0;border-collapse:collapse;margin-bottom:20px;\">";
            h += $"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}width:5%\">#</td>"
               + $"<td style=\"{ThStyle}width:30%\">Stage</td>"
               + $"<td style=\"{ThStyle}text-align:right;width:15%\">Clients</td>"
               + $"<td style=\"{ThStyle}text-align:right;width:15%\">Avg Days</td>"
               + $"<td style=\"{ThStyle}text-align:right;width:20%\">Total TCP</td>"
               + $"<td style=\"{ThStyle}width:15%\">Severity</td></tr>";

            var maxAvg = bottlenecks.Count > 0 ? bottlenecks[0].AvgDays : 1;
            for (var i = 0; i < bottlenecks.Count; i++)
            {
                var bn = bottlenecks[i];
                var barColor = i == 0 ? "#D32F2F" : i == 1 ? "#ED6C02" : "#F9A825";
                var barWidth = maxAvg > 0 ? (int)Math.Round((double)bn.AvgDays / maxAvg * 100) : 0;
                h += $"<tr style=\"background:{(i % 2 == 1 ? "#FAFAFA" : "#fff")};\">"
                   + $"<td style=\"{TdStyle}font-weight:700;color:#8B0000;\">#{i + 1}</td>"
                   + $"<td style=\"{TdStyle}font-weight:600;\">{Html(bn.Stage)}</td>"
                   + $"<td style=\"{TdRStyle}\">{bn.Count}</td>"
                   + $"<td style=\"{TdRStyle}font-weight:600;\">{bn.AvgDays} days</td>"
                   + $"<td style=\"{TdRStyle}\">{FmtCompact(bn.TotalTcp)}</td>"
                   + $"<td style=\"{TdStyle}\"><div style=\"background:#E2E8F0;border-radius:4px;height:8px;\"><div style=\"background:{barColor};border-radius:4px;height:8px;width:{barWidth}%;\"></div></div></td></tr>";
            }
            h += "</table>";
        }

        h += "<div style=\"text-align:center;padding:20px;color:#A0AEC0;font-size:11px;\">"
           + "Collection Tracker &bull; Executive Portfolio Summary &bull; Auto-generated report</div></div>";

        return h;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Report 3: Collection Performance
    // ─────────────────────────────────────────────────────────────────────

    private static string BuildCollectionPerformance(List<ClientListItemDto> mapped)
    {
        var active = mapped.Where(c => !c.IsResolved && !c.IsCancelled).ToList();
        var resolved = mapped.Where(c => c.IsResolved).ToList();

        var totalClients = mapped.Count;
        var resolvedCount = resolved.Count;
        var activeCount = active.Count;
        var completionRate = totalClients > 0 ? (decimal)resolvedCount / totalClients : 0;
        var avgResolutionDays = resolved.Count > 0 ? (int)Math.Round(resolved.Average(c => c.DaysInStage)) : 0;
        var fastestResolution = resolved.Count > 0 ? resolved.Min(c => c.DaysInStage) : 0;

        var delayReasons = mapped
            .SelectMany(c => c.DelayReasons)
            .Where(r => !string.IsNullOrWhiteSpace(r))
            .GroupBy(x => x, StringComparer.OrdinalIgnoreCase)
            .Select(g => new { Label = g.Key, Count = g.Count() })
            .OrderByDescending(x => x.Count).Take(10).ToList();

        var stages = mapped
            .Where(c => !c.IsResolved && !c.IsCancelled)
            .GroupBy(c => c.Stage, StringComparer.OrdinalIgnoreCase)
            .Select(g => new { Label = g.Key, Count = g.Count() })
            .OrderByDescending(x => x.Count).Take(10).ToList();

        var resolutionByFinancing = resolved
            .GroupBy(c => c.FinancingType, StringComparer.OrdinalIgnoreCase)
            .Select(g => new { FinancingType = g.Key, AverageDays = (int)Math.Round(g.Average(c => c.DaysInStage)), ResolvedCount = g.Count() })
            .OrderByDescending(x => x.ResolvedCount).ToList();

        decimal criticalTcp = 0, warningTcp = 0, watchTcp = 0, onTrackTcp = 0;
        int criticalC = 0, warningC = 0, watchC = 0, onTrackC = 0;
        foreach (var c in active)
        {
            var tcpVal = c.TotalContractPrice ?? 0;
            switch (c.AgingStatus)
            {
                case "critical": criticalTcp += tcpVal; criticalC++; break;
                case "warning": warningTcp += tcpVal; warningC++; break;
                case "watch": watchTcp += tcpVal; watchC++; break;
                case "ok": onTrackTcp += tcpVal; onTrackC++; break;
            }
        }

        var sb = new StringBuilder();
        sb.Append(OpenContainer());
        sb.Append(BuildReportHeader("Collection Performance Report", "Pipeline health, resolution speed, and aging tier exposure"));

        // ── Performance overview cards ──
        sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:16px;\"><tr>");
        sb.Append(KpiCell("Active Clients", activeCount.ToString(), "#1565C0", "#E3F2FD"));
        sb.Append(KpiCell("Resolved", resolvedCount.ToString(), "#2E7D32", "#E8F5E9"));
        sb.Append(KpiCell("Completion Rate", FormatPct(completionRate), "#8B0000", "rgba(139,0,0,0.08)"));
        sb.Append(KpiCell("Avg Resolution Days", avgResolutionDays.ToString(), "#ED6C02", "#FFF3E0"));
        sb.Append("</tr></table>");

        // ── Pipeline stage distribution ──
        sb.Append(SectionDivider("📊 Pipeline Stage Distribution"));
        sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px 18px;margin-bottom:16px;\">");
        var maxStageCount = stages.Count > 0 ? stages[0].Count : 1;
        foreach (var s in stages)
        {
            var width = maxStageCount > 0 ? (int)Math.Round((double)s.Count / maxStageCount * 100) : 0;
            sb.Append($"<div style=\"display:flex;align-items:center;gap:10px;padding:5px 0;font-size:12px;\">"
                    + $"<div style=\"width:32%;color:#475569;\">{Html(s.Label)}</div>"
                    + $"<div style=\"flex:1;background:#f1f5f9;border-radius:4px;height:14px;position:relative;\">"
                    + $"<div style=\"background:#8B0000;border-radius:4px;height:14px;width:{width}%;\"></div></div>"
                    + $"<div style=\"width:50px;text-align:right;font-weight:700;color:#1f2937;\">{s.Count}</div></div>");
        }
        sb.Append("</div>");

        // ── Delay reason analysis ──
        if (delayReasons.Count > 0)
        {
            sb.Append(SectionDivider("⚠ Top Delay Reasons"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px 18px;margin-bottom:16px;\">");
            var maxDr = delayReasons[0].Count;
            for (var i = 0; i < delayReasons.Count; i++)
            {
                var d = delayReasons[i];
                var width = maxDr > 0 ? (int)Math.Round((double)d.Count / maxDr * 100) : 0;
                var color = i == 0 ? "#D32F2F" : i < 3 ? "#ED6C02" : "#F9A825";
                sb.Append($"<div style=\"display:flex;align-items:center;gap:10px;padding:5px 0;font-size:12px;\">"
                        + $"<div style=\"width:32%;color:#475569;\">{Html(d.Label)}</div>"
                        + $"<div style=\"flex:1;background:#f1f5f9;border-radius:4px;height:12px;\">"
                        + $"<div style=\"background:{color};border-radius:4px;height:12px;width:{width}%;\"></div></div>"
                        + $"<div style=\"width:50px;text-align:right;font-weight:700;color:#1f2937;\">{d.Count}</div></div>");
            }
            sb.Append("</div>");
        }

        // ── Resolution by financing type ──
        if (resolutionByFinancing.Count > 0)
        {
            sb.Append(SectionDivider("⚡ Resolution Speed by Financing Type"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append($"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}\">Financing Type</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Avg Days to Resolve</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Resolved Clients</td></tr>");
            for (var i = 0; i < resolutionByFinancing.Count; i++)
            {
                var r = resolutionByFinancing[i];
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}\">{Html(r.FinancingType)}</td>"
                        + $"<td style=\"{TdRStyle}font-weight:700;\">{r.AverageDays} days</td>"
                        + $"<td style=\"{TdRStyle}\">{r.ResolvedCount}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── Aging tier breakdown ──
        sb.Append(SectionDivider("🎯 Aging Tier Exposure"));
        sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:16px;\"><tr>");
        sb.Append(AgingTierCell("Critical", criticalC, criticalTcp, "#D32F2F", "#FFEBEE"));
        sb.Append(AgingTierCell("Warning", warningC, warningTcp, "#ED6C02", "#FFF3E0"));
        sb.Append(AgingTierCell("Watch", watchC, watchTcp, "#F9A825", "#FFFDE7"));
        sb.Append(AgingTierCell("On Track", onTrackC, onTrackTcp, "#2E7D32", "#E8F5E9"));
        sb.Append("</tr></table>");

        // ── Rule-based insights ──
        sb.Append(SectionDivider("💡 Insights & Action Items"));
        sb.Append(BuildPerformanceInsights(activeCount, resolvedCount, completionRate, avgResolutionDays, fastestResolution,
            criticalC, criticalTcp, delayReasons.FirstOrDefault()?.Label, delayReasons.FirstOrDefault()?.Count ?? 0, stages.FirstOrDefault()?.Label));

        sb.Append(BuildFooter("Collection Performance"));
        sb.Append("</div>");
        return sb.ToString();
    }

    private static string BuildPerformanceInsights(
        int activeCount, int resolvedCount, decimal completionRate, int avgResolutionDays, int fastestResolution,
        int criticalCount, decimal criticalTcp, string? topDelayLabel, int topDelayCount, string? topStageLabel)
    {
        var sb = new StringBuilder();
        var items = new List<(string Color, string Text)>();

        if (completionRate >= 0.7m)
            items.Add(("#2E7D32", $"Completion rate of <strong>{FormatPct(completionRate)}</strong> is strong — {resolvedCount} of {activeCount + resolvedCount} accounts resolved."));
        else if (completionRate >= 0.4m)
            items.Add(("#ED6C02", $"Completion rate at <strong>{FormatPct(completionRate)}</strong> — room to improve. Target 70%+."));
        else
            items.Add(("#D32F2F", $"Completion rate of <strong>{FormatPct(completionRate)}</strong> is below threshold. Audit stuck stages and follow-up cadence."));

        if (criticalCount > 0)
            items.Add(("#D32F2F", $"<strong>{criticalCount} critical account(s)</strong> represent <strong>{FormatPeso(criticalTcp)}</strong> in TCP at risk — prioritize this week."));

        if (!string.IsNullOrWhiteSpace(topDelayLabel))
            items.Add(("#ED6C02", $"Top delay reason is <strong>\"{Html(topDelayLabel)}\"</strong> ({topDelayCount} accounts). Investigate root cause."));

        if (!string.IsNullOrWhiteSpace(topStageLabel))
            items.Add(("#8B0000", $"Most active clients are concentrated in stage <strong>\"{Html(topStageLabel)}\"</strong> — review for process bottleneck."));

        if (avgResolutionDays > 0)
        {
            if (fastestResolution > 0 && avgResolutionDays > fastestResolution * 2)
                items.Add(("#ED6C02", $"Average resolution is <strong>{avgResolutionDays} days</strong> vs fastest at <strong>{fastestResolution} days</strong>. Study top performers to spread best practice."));
            else
                items.Add(("#2E7D32", $"Average resolution sits at <strong>{avgResolutionDays} days</strong>, in line with fastest at {fastestResolution} days."));
        }

        foreach (var (color, text) in items)
        {
            sb.Append($"<div style=\"background:#fff;border:1px solid #e5e7eb;border-left:4px solid {color};border-radius:8px;padding:10px 14px;margin-bottom:8px;font-size:12.5px;color:#475569;line-height:1.55;\">{text}</div>");
        }
        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Report 4: Strategic Recommendations
    // ─────────────────────────────────────────────────────────────────────

    private static async Task<string> BuildStrategicRecommendationsAsync(
        List<ClientListItemDto> mapped,
        IClientRepository clientRepository,
        int? projectId,
        Dictionary<string, HashSet<string>> bucketMap,
        CancellationToken cancellationToken)
    {
        var projects = await clientRepository.GetProjectsAsync(cancellationToken);
        if (projectId.HasValue)
            projects = projects.Where(p => p.Id == projectId.Value).ToList();

        var perProject = new List<ProjectStratRow>();
        var unsoldUnits = new List<UnsoldUnitRow>();
        decimal totalValue = 0, totalForAcceptance = 0, totalFullyPaid = 0, totalForCancellation = 0;
        decimal totalDelivered = 0, totalOnProcess = 0, totalForProcess = 0;

        foreach (var project in projects)
        {
            var units = await clientRepository.GetProjectUnitsAsync(project.Id, cancellationToken);
            var projectClients = mapped.Where(c => c.ProjectId == project.Id).ToList();
            var cancelBucket = GetBucket(bucketMap, "cancellation");
            var occupiedUnits = projectClients
                .Where(c => !cancelBucket.Contains(c.Stage ?? ""))
                .Select(c => c.Unit).ToHashSet(StringComparer.OrdinalIgnoreCase);

            decimal unsold = 0;
            int unsoldCount = 0;
            foreach (var unit in units)
            {
                if (!occupiedUnits.Contains(unit.Name))
                {
                    unsold += unit.TotalContractPrice ?? 0;
                    unsoldCount++;
                    unsoldUnits.Add(new UnsoldUnitRow(project.Name, unit.Name, unit.TotalContractPrice ?? 0));
                }
            }

            decimal forAcceptance = 0, fullyPaid = 0, forCancellation = 0;
            decimal delivered = 0, onProcess = 0, forProcess = 0;
            foreach (var c in projectClients)
            {
                var tcp = c.TotalContractPrice ?? 0;
                var stage = c.Stage ?? "";
                if (cancelBucket.Contains(stage)) continue;
                if (GetBucket(bucketMap, "resolved").Contains(stage) || c.IsResolved) fullyPaid += tcp;
                else forAcceptance += tcp;

                if (GetBucket(bucketMap, "delivered").Contains(c.Stage)) delivered += tcp;
                if (GetBucket(bucketMap, "on-process").Contains(c.Stage)) onProcess += tcp;
                if (GetBucket(bucketMap, "for-process").Contains(c.Stage)) forProcess += tcp;
            }

            var total = unsold + forAcceptance + fullyPaid + forCancellation;
            perProject.Add(new ProjectStratRow(project.Name, unsoldCount, unsold, forAcceptance, fullyPaid, forCancellation, total));

            totalForAcceptance += forAcceptance; totalFullyPaid += fullyPaid;
            totalForCancellation += forCancellation; totalValue += total;
            totalDelivered += delivered; totalOnProcess += onProcess; totalForProcess += forProcess;
        }

        var soldBase = totalValue;
        var deliveryBase = totalForAcceptance + totalFullyPaid;
        var cancBase = totalForAcceptance + totalFullyPaid + totalForCancellation;
        var soldRate = soldBase > 0 ? (totalForAcceptance + totalFullyPaid) / soldBase : 0;
        var deliveryRate = deliveryBase > 0 ? totalDelivered / deliveryBase : 0;
        var cancellationRate = cancBase > 0 ? totalForCancellation / cancBase : 0;
        var pipelineValue = totalOnProcess + totalForProcess;

        // Risk matrix
        var tcps = mapped.Select(c => c.TotalContractPrice ?? 0).Where(t => t > 0).OrderBy(t => t).ToList();
        var median = tcps.Count > 0 ? tcps[tcps.Count / 2] : 0;

        var hvhr = mapped.Where(c => (c.TotalContractPrice ?? 0) > median && c.AgingStatus == "critical").ToList();
        var hvlr = mapped.Where(c => (c.TotalContractPrice ?? 0) > median && (c.AgingStatus == "ok" || c.AgingStatus == "watch")).ToList();
        var lvhr = mapped.Where(c => (c.TotalContractPrice ?? 0) <= median && c.AgingStatus == "critical").ToList();
        var lvlr = mapped.Where(c => (c.TotalContractPrice ?? 0) <= median && (c.AgingStatus == "ok" || c.AgingStatus == "watch")).ToList();

        var atRisk = mapped
            .Where(c => c.AgingStatus is "critical" or "warning")
            .OrderByDescending(c => c.TotalContractPrice ?? 0)
            .Take(10)
            .ToList();

        var unsoldByProject = unsoldUnits
            .GroupBy(u => u.ProjectName)
            .Select(g => new { Project = g.Key, Count = g.Count(), TotalTcp = g.Sum(u => u.Tcp), Units = g.Select(u => u.UnitName).Take(8).ToList() })
            .OrderByDescending(x => x.TotalTcp)
            .ToList();

        var sb = new StringBuilder();
        sb.Append(OpenContainer());
        sb.Append(BuildReportHeader("Strategic Recommendations Report", "Board-level findings and prioritized action plan"));

        // ── Portfolio KPIs ──
        sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:16px;\"><tr>");
        sb.Append(KpiCell("Portfolio Value", FmtCompact(totalValue), "#8B0000", "rgba(139,0,0,0.08)"));
        sb.Append(KpiCell("Sold Rate", FormatPct(soldRate), "#2E7D32", "#E8F5E9"));
        sb.Append(KpiCell("Cancellation Rate", FormatPct(cancellationRate), "#D32F2F", "#FFEBEE"));
        sb.Append(KpiCell("Pipeline", FmtCompact(pipelineValue), "#ED6C02", "#FFF3E0"));
        sb.Append("</tr></table>");

        // ── Risk matrix ──
        sb.Append(SectionDivider("🎯 Financial Risk Matrix"));
        sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:16px;\"><tr>");
        sb.Append(RiskQuadrant("High Value × High Risk", hvhr.Count, hvhr.Sum(c => c.TotalContractPrice ?? 0), "#D32F2F", "#FFEBEE", "Top priority"));
        sb.Append(RiskQuadrant("High Value × Low Risk", hvlr.Count, hvlr.Sum(c => c.TotalContractPrice ?? 0), "#2E7D32", "#E8F5E9", "Protect"));
        sb.Append("</tr><tr><td colspan=\"2\" style=\"height:8px;\"></td></tr><tr>");
        sb.Append(RiskQuadrant("Low Value × High Risk", lvhr.Count, lvhr.Sum(c => c.TotalContractPrice ?? 0), "#ED6C02", "#FFF3E0", "Triage by volume"));
        sb.Append(RiskQuadrant("Low Value × Low Risk", lvlr.Count, lvlr.Sum(c => c.TotalContractPrice ?? 0), "#1565C0", "#E3F2FD", "Maintain"));
        sb.Append("</tr></table>");

        // ── Unsold Inventory ──
        if (unsoldByProject.Count > 0)
        {
            sb.Append(SectionDivider("🏠 Unsold Inventory Exposure by Project"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append($"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}\">Project</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Unsold Units</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Total Unsold TCP</td>"
                    + $"<td style=\"{ThStyle}\">Sample Units</td></tr>");
            for (var i = 0; i < unsoldByProject.Count; i++)
            {
                var p = unsoldByProject[i];
                var highlight = p.Count > 5 ? "background:#FFF3E0;" : (i % 2 == 1 ? "background:#fafafa;" : "");
                sb.Append($"<tr style=\"{highlight}\">"
                        + $"<td style=\"{TdStyle}font-weight:600;\">{Html(p.Project)}</td>"
                        + $"<td style=\"{TdRStyle}font-weight:700;color:{(p.Count > 5 ? "#ED6C02" : "#1f2937")};\">{p.Count}</td>"
                        + $"<td style=\"{TdRStyle}\">{FormatPeso(p.TotalTcp)}</td>"
                        + $"<td style=\"{TdStyle}font-size:11px;color:#64748b;\">{Html(string.Join(", ", p.Units))}{(p.Count > 8 ? $" +{p.Count - 8} more" : "")}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── Top at-risk accounts ──
        if (atRisk.Count > 0)
        {
            sb.Append(SectionDivider("🚨 Top At-Risk Accounts (by TCP)"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append($"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}\">Client</td>"
                    + $"<td style=\"{ThStyle}\">Project / Unit</td>"
                    + $"<td style=\"{ThStyle}\">Stage</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Days</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">TCP</td>"
                    + $"<td style=\"{ThStyle}\">Status</td></tr>");
            for (var i = 0; i < atRisk.Count; i++)
            {
                var c = atRisk[i];
                var statusColor = c.AgingStatus == "critical" ? "#D32F2F" : "#ED6C02";
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}font-weight:600;\">{Html(c.Name)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(c.ProjectName)} / {Html(c.Unit)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(c.Stage)}</td>"
                        + $"<td style=\"{TdRStyle}\">{c.DaysInStage}</td>"
                        + $"<td style=\"{TdRStyle}font-weight:700;\">{FormatPeso(c.TotalContractPrice ?? 0)}</td>"
                        + $"<td style=\"{TdStyle}\"><span style=\"background:{statusColor};color:#fff;padding:2px 8px;border-radius:10px;font-size:9px;font-weight:700;letter-spacing:0.4px;\">{c.AgingStatus.ToUpper()}</span></td></tr>");

                if (c.DelayReasons.Count > 0 || !string.IsNullOrWhiteSpace(c.NextAction))
                {
                    sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\"><td colspan=\"6\" style=\"padding:0 14px 8px;font-size:11px;color:#64748b;\">");
                    if (c.DelayReasons.Count > 0)
                        sb.Append($"<div><strong>Delay:</strong> {Html(string.Join(", ", c.DelayReasons))}</div>");
                    if (!string.IsNullOrWhiteSpace(c.NextAction))
                        sb.Append($"<div><strong>Next:</strong> {Html(c.NextAction)}</div>");
                    sb.Append("</td></tr>");
                }
            }
            sb.Append("</table></div>");
        }

        // ── Prioritized action plan ──
        sb.Append(SectionDivider("📋 Prioritized Action Plan"));
        sb.Append(BuildStrategicActionPlan(
            hvhr.Count, hvhr.Sum(c => c.TotalContractPrice ?? 0),
            cancellationRate, totalForCancellation,
            unsoldByProject.Sum(p => p.TotalTcp), unsoldByProject.Count,
            pipelineValue, atRisk));

        // ── Revenue recovery opportunities ──
        sb.Append(SectionDivider("💰 Revenue Recovery Opportunities"));
        var unsoldTotal = unsoldByProject.Sum(p => p.TotalTcp);
        var atRiskTotal = atRisk.Sum(c => c.TotalContractPrice ?? 0);
        sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px 18px;margin-bottom:16px;font-size:13px;color:#475569;line-height:1.7;\">");
        sb.Append($"<div>Unsold inventory represents <strong style=\"color:#1f2937;\">{FormatPeso(unsoldTotal)}</strong> in latent revenue — a structured push could convert a portion within 60-90 days.</div>");
        sb.Append($"<div style=\"margin-top:6px;\">At-risk accounts hold <strong style=\"color:#1f2937;\">{FormatPeso(atRiskTotal)}</strong> in TCP. Recovering even 30% via direct outreach is <strong style=\"color:#2E7D32;\">{FormatPeso(atRiskTotal * 0.3m)}</strong>.</div>");
        sb.Append($"<div style=\"margin-top:6px;\">Pipeline carries <strong style=\"color:#1f2937;\">{FormatPeso(pipelineValue)}</strong> on the bank/processing side — accelerating average cycle time materially compresses cash collection.</div>");
        sb.Append("</div>");

        sb.Append(BuildFooter("Strategic Recommendations"));
        sb.Append("</div>");
        return sb.ToString();
    }

    private sealed record ProjectStratRow(string Name, int UnsoldCount, decimal Unsold, decimal ForAcceptance, decimal FullyPaid, decimal ForCancellation, decimal Total);
    private sealed record UnsoldUnitRow(string ProjectName, string UnitName, decimal Tcp);

    private static string BuildStrategicActionPlan(
        int hvhrCount, decimal hvhrTcp,
        decimal cancellationRate, decimal cancellationTcp,
        decimal unsoldTcp, int unsoldProjectCount,
        decimal pipelineValue, List<ClientListItemDto> atRisk)
    {
        var sb = new StringBuilder();
        var actions = new List<(string Priority, string Color, string Title, string Detail, string Impact, string Timeline)>();

        if (hvhrCount > 0)
            actions.Add(("CRITICAL", "#D32F2F",
                $"Direct executive outreach on {hvhrCount} high-value × high-risk account(s)",
                "Assign a sponsor per account; weekly check-ins until status improves.",
                FormatPeso(hvhrTcp), "Immediate"));

        if (cancellationRate > 0.10m)
            actions.Add(("HIGH", "#ED6C02",
                $"Cancellation rate at {FormatPct(cancellationRate)} exceeds 10% threshold",
                "Root-cause review on top delay reasons; tighten stage gating before move-out.",
                FormatPeso(cancellationTcp), "Short-term (30 days)"));

        if (unsoldTcp > 0 && unsoldProjectCount > 0)
            actions.Add(("HIGH", "#ED6C02",
                $"Activate unsold-inventory push across {unsoldProjectCount} project(s)",
                "Targeted marketing + broker incentives for high-exposure projects.",
                FormatPeso(unsoldTcp), "Short-term (60 days)"));

        if (pipelineValue > 0)
            actions.Add(("MEDIUM", "#8B0000",
                "Compress bank-approval cycle time",
                "Standing weekly review with banks/Pag-IBIG to surface bottlenecks; escalate stalled files >45 days.",
                FormatPeso(pipelineValue), "Medium-term (90 days)"));

        var topAtRisk = atRisk.Take(3).ToList();
        if (topAtRisk.Count > 0)
        {
            var names = string.Join(", ", topAtRisk.Select(c => c.Name));
            var tcpSum = topAtRisk.Sum(c => c.TotalContractPrice ?? 0);
            actions.Add(("CRITICAL", "#D32F2F",
                "Personally close out top 3 at-risk accounts",
                $"Accounts: {Html(names)}",
                FormatPeso(tcpSum), "Immediate"));
        }

        actions.Add(("STRATEGIC", "#1565C0",
            "Institute weekly KPI review",
            "Track cancellation rate, sold rate, days-in-stage, and pipeline velocity each week to catch drift early.",
            "Operational lift", "Ongoing"));

        var i = 1;
        foreach (var (priority, color, title, detail, impact, timeline) in actions)
        {
            sb.Append($"<div style=\"background:#fff;border:1px solid #e5e7eb;border-left:4px solid {color};border-radius:8px;padding:12px 16px;margin-bottom:8px;\">"
                    + $"<div style=\"display:flex;justify-content:space-between;align-items:flex-start;gap:10px;flex-wrap:wrap;\">"
                    + $"<div style=\"flex:1;min-width:200px;\"><span style=\"display:inline-block;background:{color};color:#fff;font-size:10px;font-weight:800;padding:2px 8px;border-radius:10px;letter-spacing:0.6px;\">{priority}</span>"
                    + $"<span style=\"font-size:11px;color:#9ca3af;margin-left:6px;\">#{i}</span>"
                    + $"<div style=\"font-size:13px;font-weight:700;color:#1f2937;margin-top:6px;\">{title}</div>"
                    + $"<div style=\"font-size:12px;color:#475569;margin-top:4px;line-height:1.55;\">{detail}</div></div>"
                    + $"<div style=\"text-align:right;min-width:160px;\">"
                    + $"<div style=\"font-size:10px;color:#64748b;font-weight:700;text-transform:uppercase;\">Impact</div>"
                    + $"<div style=\"font-size:13px;font-weight:800;color:{color};\">{impact}</div>"
                    + $"<div style=\"font-size:11px;color:#9ca3af;margin-top:4px;\">{timeline}</div></div></div></div>");
            i++;
        }
        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Report 5: Collection Forecast
    // ─────────────────────────────────────────────────────────────────────

    private static async Task<string> BuildCollectionForecastAsync(
        List<ClientListItemDto> mapped,
        IClientRepository clientRepository,
        int? projectId,
        Dictionary<string, HashSet<string>> bucketMap,
        CancellationToken cancellationToken)
    {
        var projects = await clientRepository.GetProjectsAsync(cancellationToken);
        if (projectId.HasValue)
            projects = projects.Where(p => p.Id == projectId.Value).ToList();

        var approvedBucket = GetBucket(bucketMap, "approved");
        var onProcessBucket = GetBucket(bucketMap, "on-process");
        var forProcessBucket = GetBucket(bucketMap, "for-process");
        var deliveredBucket = GetBucket(bucketMap, "delivered");

        var deliveredClients = mapped.Where(c => deliveredBucket.Contains(c.Stage) || c.IsResolved).ToList();
        var avgDaysToDeliver = deliveredClients.Count > 0
            ? (int)Math.Round(deliveredClients.Average(c => c.DaysInStage))
            : 60;

        var perProject = new List<ForecastRow>();
        decimal totalApproved = 0, totalOnProcess = 0, totalForProcess = 0;
        int totalApprovedCount = 0, totalOnProcessCount = 0, totalForProcessCount = 0;

        foreach (var project in projects)
        {
            var projectClients = mapped.Where(c => c.ProjectId == project.Id).ToList();
            var approved = projectClients.Where(c => approvedBucket.Contains(c.Stage)).ToList();
            var onProcess = projectClients.Where(c => onProcessBucket.Contains(c.Stage)).ToList();
            var forProcess = projectClients.Where(c => forProcessBucket.Contains(c.Stage)).ToList();

            var approvedTcp = approved.Sum(c => c.TotalContractPrice ?? 0);
            var onProcessTcp = onProcess.Sum(c => c.TotalContractPrice ?? 0);
            var forProcessTcp = forProcess.Sum(c => c.TotalContractPrice ?? 0);

            perProject.Add(new ForecastRow(project.Name,
                approved.Count, approvedTcp,
                onProcess.Count, onProcessTcp,
                forProcess.Count, forProcessTcp,
                avgDaysToDeliver));

            totalApproved += approvedTcp; totalApprovedCount += approved.Count;
            totalOnProcess += onProcessTcp; totalOnProcessCount += onProcess.Count;
            totalForProcess += forProcessTcp; totalForProcessCount += forProcess.Count;
        }

        // Project 90-day collections — eligibility by daysInStage bucket
        var approvedAll = mapped.Where(c => approvedBucket.Contains(c.Stage)).ToList();
        var projections = new List<(string Month, decimal Amount, int Count)>();
        var today = DateTime.UtcNow.Date;
        for (var monthOffset = 1; monthOffset <= 3; monthOffset++)
        {
            var targetMonth = today.AddMonths(monthOffset);
            var cutoffDays = monthOffset * 30;
            var eligible = approvedAll
                .Where(c => c.DaysInStage + cutoffDays >= avgDaysToDeliver && c.DaysInStage < cutoffDays + avgDaysToDeliver)
                .ToList();
            if (monthOffset == 1)
                eligible = approvedAll.Where(c => c.DaysInStage >= avgDaysToDeliver * 0.7).Take(approvedAll.Count / 3 + 1).ToList();

            projections.Add((targetMonth.ToString("MMM yyyy"), eligible.Sum(c => c.TotalContractPrice ?? 0), eligible.Count));
        }

        // Risk: stalled approved accounts
        var stalled = approvedAll
            .Where(c => c.DaysInStage > avgDaysToDeliver)
            .OrderByDescending(c => c.DaysInStage)
            .Take(8)
            .ToList();

        var sb = new StringBuilder();
        sb.Append(OpenContainer());
        sb.Append(BuildReportHeader("Sales Collection Forecast", "Pipeline value, 90-day projection, and stalled-account risk"));

        // ── Pipeline summary cards ──
        sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-bottom:16px;\"><tr>");
        sb.Append(KpiCell("Approved", FmtCompact(totalApproved), "#2E7D32", "#E8F5E9"));
        sb.Append(KpiCell("On Process", FmtCompact(totalOnProcess), "#1565C0", "#E3F2FD"));
        sb.Append(KpiCell("For Process", FmtCompact(totalForProcess), "#ED6C02", "#FFF3E0"));
        sb.Append(KpiCell("Total Pipeline", FmtCompact(totalApproved + totalOnProcess + totalForProcess), "#8B0000", "rgba(139,0,0,0.08)"));
        sb.Append("</tr></table>");
        sb.Append($"<div style=\"text-align:center;font-size:11px;color:#64748b;margin-bottom:16px;\">Historical average days approved → delivered: <strong style=\"color:#1f2937;\">{avgDaysToDeliver}</strong></div>");

        // ── Per-project forecast ──
        if (perProject.Count > 0)
        {
            sb.Append(SectionDivider("📍 Per-Project Pipeline"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append($"<tr style=\"background:#F7FAFC;\"><td style=\"{ThStyle}\">Project</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Approved</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">On Process</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">For Process</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Est. Days</td></tr>");
            for (var i = 0; i < perProject.Count; i++)
            {
                var p = perProject[i];
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}font-weight:600;\">{Html(p.Project)}</td>"
                        + $"<td style=\"{TdRStyle}\">{p.ApprovedCount} &middot; {FmtCompact(p.ApprovedTcp)}</td>"
                        + $"<td style=\"{TdRStyle}\">{p.OnProcessCount} &middot; {FmtCompact(p.OnProcessTcp)}</td>"
                        + $"<td style=\"{TdRStyle}\">{p.ForProcessCount} &middot; {FmtCompact(p.ForProcessTcp)}</td>"
                        + $"<td style=\"{TdRStyle}font-weight:700;color:#8B0000;\">{p.AvgDaysToDeliver}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── 90-day projection chart ──
        sb.Append(SectionDivider("📈 90-Day Collection Projection"));
        var maxProj = projections.Count > 0 ? projections.Max(p => p.Amount) : 0;
        sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:18px 22px;margin-bottom:16px;\">");
        foreach (var p in projections)
        {
            var width = maxProj > 0 ? (int)Math.Round((double)(p.Amount / maxProj) * 100) : 0;
            sb.Append($"<div style=\"margin-bottom:14px;\">"
                    + $"<div style=\"display:flex;justify-content:space-between;align-items:baseline;font-size:12px;color:#475569;margin-bottom:4px;\">"
                    + $"<span><strong style=\"color:#1f2937;\">{p.Month}</strong> &middot; {p.Count} client(s)</span>"
                    + $"<span style=\"font-weight:800;color:#1f2937;\">{FormatPeso(p.Amount)}</span></div>"
                    + $"<div style=\"background:#f1f5f9;border-radius:6px;height:16px;overflow:hidden;\">"
                    + $"<div style=\"background:linear-gradient(90deg,#8B0000,#D32F2F);height:16px;width:{width}%;border-radius:6px;\"></div></div></div>");
        }
        sb.Append("</div>");

        // ── Risk: stalled accounts ──
        if (stalled.Count > 0)
        {
            sb.Append(SectionDivider("⚠ Risk Factors — Stalled Approved Accounts"));
            sb.Append("<div style=\"background:#fff;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;margin-bottom:16px;\">");
            sb.Append("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;\">");
            sb.Append($"<tr style=\"background:#FFF3E0;\"><td style=\"{ThStyle}\">Client</td>"
                    + $"<td style=\"{ThStyle}\">Project / Unit</td>"
                    + $"<td style=\"{ThStyle}\">Stage</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">Days</td>"
                    + $"<td style=\"{ThStyle}text-align:right;\">TCP</td></tr>");
            for (var i = 0; i < stalled.Count; i++)
            {
                var c = stalled[i];
                sb.Append($"<tr style=\"background:{(i % 2 == 1 ? "#fafafa" : "#fff")};\">"
                        + $"<td style=\"{TdStyle}font-weight:600;\">{Html(c.Name)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(c.ProjectName)} / {Html(c.Unit)}</td>"
                        + $"<td style=\"{TdStyle}\">{Html(c.Stage)}</td>"
                        + $"<td style=\"{TdRStyle}color:#D32F2F;font-weight:700;\">{c.DaysInStage}</td>"
                        + $"<td style=\"{TdRStyle}\">{FormatPeso(c.TotalContractPrice ?? 0)}</td></tr>");
            }
            sb.Append("</table></div>");
        }

        // ── Rule-based recommendations ──
        sb.Append(SectionDivider("💡 Recommendations to Accelerate Collections"));
        sb.Append(BuildForecastRecommendations(stalled.Count, stalled.Sum(c => c.TotalContractPrice ?? 0),
            totalApproved, totalOnProcess + totalForProcess, avgDaysToDeliver, projections));

        sb.Append(BuildFooter("Collection Forecast"));
        sb.Append("</div>");
        return sb.ToString();
    }

    private sealed record ForecastRow(string Project,
        int ApprovedCount, decimal ApprovedTcp,
        int OnProcessCount, decimal OnProcessTcp,
        int ForProcessCount, decimal ForProcessTcp,
        int AvgDaysToDeliver);

    private static string BuildForecastRecommendations(
        int stalledCount, decimal stalledTcp,
        decimal approvedTotal, decimal pipelineTotal,
        int avgDaysToDeliver, List<(string Month, decimal Amount, int Count)> projections)
    {
        var sb = new StringBuilder();
        var recs = new List<(string Color, string Title, string Body)>();

        if (stalledCount > 0)
            recs.Add(("#D32F2F",
                $"Escalate {stalledCount} stalled approved account(s) ({FormatPeso(stalledTcp)})",
                $"These exceeded the historical average of {avgDaysToDeliver} days. Direct calls to bank/Pag-IBIG officers this week."));

        if (approvedTotal > 0)
            recs.Add(("#ED6C02",
                $"Convert {FormatPeso(approvedTotal)} of approved pipeline within 30-60 days",
                "Approved status is closest to cash — confirm signing schedule and BV/SI logistics now."));

        if (pipelineTotal > 0)
            recs.Add(("#8B0000",
                "Tighten the front-end of the pipeline",
                "Document compliance and bank submission are the longest stages — assign a doc-runner role to shave 5-10 days off cycle time."));

        var firstMonth = projections.Count > 0 ? projections[0] : default;
        if (firstMonth.Count > 0)
            recs.Add(("#2E7D32",
                $"Lock in {firstMonth.Month}: ~{FormatPeso(firstMonth.Amount)} projected from {firstMonth.Count} client(s)",
                "Confirm with each client 2 weeks ahead of expected closing — pre-empt last-minute documentation gaps."));

        foreach (var (color, title, body) in recs)
        {
            sb.Append($"<div style=\"background:#fff;border:1px solid #e5e7eb;border-left:4px solid {color};border-radius:8px;padding:12px 16px;margin-bottom:8px;\">"
                    + $"<div style=\"font-size:13px;font-weight:700;color:#1f2937;\">{title}</div>"
                    + $"<div style=\"font-size:12px;color:#475569;margin-top:4px;line-height:1.55;\">{body}</div></div>");
        }
        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Shared HTML helpers
    // ─────────────────────────────────────────────────────────────────────

    private const string ThStyle = "padding:8px 12px;font-size:11px;font-weight:700;color:#4A5568;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #E2E8F0;";
    private const string TdStyle = "padding:7px 12px;font-size:12px;color:#2D3748;";
    private const string TdRStyle = "padding:7px 12px;font-size:12px;color:#2D3748;text-align:right;font-variant-numeric:tabular-nums;";

    private static string OpenContainer() =>
        "<div style=\"font-family:Inter,Segoe UI,Arial,sans-serif;color:#1A202C;max-width:900px;margin:0 auto;\">";

    private static string BuildReportHeader(string title, string subtitle) =>
        $"<div style=\"background:linear-gradient(135deg,#1a0000 0%,#8B0000 100%);padding:24px 28px;border-radius:12px;margin-bottom:20px;\">"
        + $"<h1 style=\"margin:0;color:#fff;font-size:20px;font-weight:700;\">{title}</h1>"
        + $"<p style=\"margin:6px 0 0;color:rgba(255,255,255,0.75);font-size:12.5px;\">{subtitle}</p>"
        + $"<p style=\"margin:2px 0 0;color:rgba(255,255,255,0.55);font-size:11px;\">Generated {DateTime.UtcNow:MMM d, yyyy h:mm tt} UTC</p></div>";

    private static string BuildFooter(string reportName) =>
        $"<div style=\"text-align:center;padding:20px;color:#A0AEC0;font-size:11px;\">Collection Tracker &bull; {reportName} &bull; Auto-generated report</div>";

    private static string SectionDivider(string label) =>
        $"<div style=\"text-align:center;margin:24px 0 14px;color:#475569;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:1.2px;\">{label}</div>";

    private static string SubBanner(string label) =>
        $"<div style=\"background:#F7FAFC;padding:10px 14px;border-bottom:1px solid #E2E8F0;font-size:11px;font-weight:800;color:#8B0000;letter-spacing:1px;\">{label}</div>";

    private static string KpiHero(string label, string value, string subtitle) =>
        $"<div style=\"background:#FFFBF0;border-left:4px solid #D4A017;border-radius:10px;padding:18px 22px;margin-bottom:14px;\">"
        + $"<div style=\"font-size:11px;color:#8B7D3C;font-weight:600;text-transform:uppercase;letter-spacing:1px;\">{label}</div>"
        + $"<div style=\"font-size:26px;font-weight:800;color:#1A202C;margin:4px 0;\">{value}</div>"
        + $"<div style=\"font-size:12px;color:#718096;\">{subtitle}</div></div>";

    private static string KpiCell(string label, string value, string color, string bg) =>
        $"<td style=\"width:25%;padding-right:8px;\">"
        + $"<div style=\"background:{bg};border-left:3px solid {color};border-radius:8px;padding:14px 16px;\">"
        + $"<div style=\"font-size:10px;color:{color};font-weight:700;text-transform:uppercase;letter-spacing:0.5px;\">{label}</div>"
        + $"<div style=\"font-size:20px;font-weight:800;color:{color};margin-top:2px;font-variant-numeric:tabular-nums;\">{value}</div></div></td>";

    private static string AgingTierCell(string label, int count, decimal tcp, string color, string bg) =>
        $"<td style=\"width:25%;padding-right:8px;\">"
        + $"<div style=\"background:{bg};border-left:3px solid {color};border-radius:8px;padding:14px 16px;\">"
        + $"<div style=\"font-size:10px;color:{color};font-weight:700;text-transform:uppercase;letter-spacing:0.5px;\">{label}</div>"
        + $"<div style=\"font-size:18px;font-weight:800;color:{color};margin-top:2px;font-variant-numeric:tabular-nums;\">{FmtCompact(tcp)}</div>"
        + $"<div style=\"font-size:11px;color:#64748b;margin-top:2px;\">{count} client(s)</div></div></td>";

    private static string RiskQuadrant(string label, int count, decimal tcp, string color, string bg, string note) =>
        $"<td style=\"width:50%;padding-right:8px;\">"
        + $"<div style=\"background:{bg};border-left:3px solid {color};border-radius:8px;padding:14px 18px;\">"
        + $"<div style=\"font-size:11px;color:{color};font-weight:800;text-transform:uppercase;letter-spacing:0.6px;\">{label}</div>"
        + $"<div style=\"font-size:18px;font-weight:800;color:#1f2937;margin-top:4px;\">{count} <span style=\"font-size:11px;color:#64748b;font-weight:600;\">accounts</span></div>"
        + $"<div style=\"font-size:14px;font-weight:700;color:{color};margin-top:2px;\">{FormatPeso(tcp)}</div>"
        + $"<div style=\"font-size:11px;color:#64748b;font-style:italic;margin-top:4px;\">{note}</div></div></td>";

    private static string FmtCompact(decimal value)
    {
        var abs = Math.Abs(value);
        if (abs >= 1_000_000m) return $"₱{value / 1_000_000m:F1}M";
        if (abs >= 1_000m) return $"₱{value / 1_000m:F0}K";
        return $"₱{value:F0}";
    }

    private static string FmtOrBlank(decimal value) => value > 0 ? FormatPeso(value) : "";
    private static string FmtDate(DateTime d) => d.ToString("MM/dd/yyyy");

    private static string FormatPeso(decimal value) => $"₱{value:N2}";

    private static string FormatPct(decimal value) => $"{value * 100:F1}%";

    private static string Html(string? s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        return s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");
    }
}
